version: 2

project_name: mercury

before:
  hooks:
    - go test ./...

builds:
  - id: mercury
    main: .
    binary: mercury
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/tarrence/mercury-cli/internal/version.version={{ .Version }}
      - -X github.com/tarrence/mercury-cli/internal/version.commitSHA={{ .Commit }}
      - -X github.com/tarrence/mercury-cli/internal/version.buildDate={{ .Date }}

archives:
  - id: mercury
    builds:
      - mercury
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
